In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
data = pd.read_csv('rail_v5.csv')

In [3]:
data.sort_values(['metric','model combo']).head()

metric  metric ticker metric calcrt    model combo  \
2596  CSX Corp  CSX US Equity         IS010  [  0  14 153]   
2597  CSX Corp  CSX US Equity         IS010  [  0  14 153]   
2598  CSX Corp  CSX US Equity         IS010  [  0  14 153]   
2644  CSX Corp  CSX US Equity         IS010  [  0  61 152]   
2645  CSX Corp  CSX US Equity         IS010  [  0  61 152]   

                                       driver name  driver id   driver ticker  \
2596                                   Nominal GDP          0  GDP CUR$ Index   
2597  Segment Revenue per Carload CSX - Intermodal         14   CSX US Equity   
2598             Average Revenue per Carload - CSX        153             NaN   
2644                                   Nominal GDP          0  GDP CUR$ Index   
2645         Average System Dwell Time - CSX Corps         61   CSX US Equity   

     driver calcrt driver transformation  cofficient    ...     \
2596         PR005                   NaN      0.1539    ...      
2597         BI047                   NaN      0.0748    ...      
2598           NaN                   NaN      0.5481    ...      
2644         PR005                   NaN      0.0000    ...      
2645         M0290                   NaN      0.0000    ...      

      harveycollier_test                                    trailing_rscore  \
2596              0.3047  0.7353|0.7539|0.8168|0.8324|0.8383|0.8383|0.84...   
2597              0.3047  0.7353|0.7539|0.8168|0.8324|0.8383|0.8383|0.84...   
2598              0.3047  0.7353|0.7539|0.8168|0.8324|0.8383|0.8383|0.84...   
2644              0.1693  0.3999|0.4415|0.4756|0.6754|0.7603|0.7544|0.77...   
2645              0.1693  0.3999|0.4415|0.4756|0.6754|0.7603|0.7544|0.77...   

     driver_freqency combo_size  pvalue random_metric_pvalue  \
2596               Q          3  0.0000                    1   
2597               Q          3  0.0000                    1   
2598               Q          3  0.0000                    1   
2644               Q          3  0.0378                    1   
2645               Q          3  0.0378                    1   

      random_driver_pvalue correlation rscore_raw  coef_raw  
2596                     1      0.8954     0.5312    0.1229  
2597                     1      0.2667     0.5312    0.0000  
2598                     1      0.8581     0.5312    0.0000  
2644                     1      0.8954     0.5179   -0.0206  
2645                     1     -0.4718     0.5179    0.0000  

[5 rows x 26 columns]

In [4]:
data['absCorr'] = np.abs(data['correlation'])

In [5]:
df = data[(data['rscore']>0.85) & (data['harveycollier_test']>.05)]

In [6]:
df.columns

Index([u'metric', u'metric ticker', u'metric calcrt', u'model combo',
       u'driver name', u'driver id', u'driver ticker', u'driver calcrt',
       u'driver transformation', u'cofficient', u'rscore', u'predicted_metric',
       u'actual_metric', u'original_metric', u'original_dirver', u'periods',
       u'harveycollier_test', u'trailing_rscore', u'driver_freqency',
       u'combo_size', u'pvalue', u'random_metric_pvalue',
       u'random_driver_pvalue', u'correlation', u'rscore_raw', u'coef_raw',
       u'absCorr'],
      dtype='object')

In [7]:
driverCount = df.groupby(['driver id'])['driver id'].count()*1./len(df)
df.sort_values(['metric','model combo']).head()
#df['driver id'].map(driverCount)
#df['dFeq'] = 0
df['dFreq'] = df['driver id'].map(driverCount)
df.head()
# print driverCount.head()

/Users/kmacneneyjr/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


metric  metric ticker metric calcrt model combo  \
0   Canadian National Railway Co  CNR CN Equity         IS010   [ 23 149]   
1   Canadian National Railway Co  CNR CN Equity         IS010   [ 23 149]   
7   Canadian National Railway Co  CNR CN Equity         IS010   [ 80 123]   
8   Canadian National Railway Co  CNR CN Equity         IS010   [ 80 123]   
12  Canadian National Railway Co  CNR CN Equity         IS010     [23 95]   

                                          driver name  driver id  \
0   Segment Revenue per Carload Canadian National ...         23   
1   Operating Metrics - GTMs per Fuel Gallons Cons...        149   
7                             East Coast Diesel Price         80   
8                            BI NA Rail Fre Trans Cmp        123   
12  Segment Revenue per Carload Canadian National ...         23   

     driver ticker driver calcrt driver transformation  cofficient    ...     \
0    CNR CN Equity         BI047                   NaN      0.6837    ...      
1    CNR CN Equity        Manual                Static      0.3129    ...      
7   USRD1DSL Index         PR005                   NaN     -0.2273    ...      
8   BIRAILNC Index         PR005                   NaN      1.0122    ...      
12   CNR CN Equity         BI047                   NaN      0.8976    ...      

    driver_freqency combo_size pvalue random_metric_pvalue  \
0                 Q          2    0.0                    1   
1                 Q          2    0.0                    1   
7                 W          2    0.0                    1   
8                 D          2    0.0                    1   
12                Q          2    0.0                    1   

   random_driver_pvalue correlation  rscore_raw coef_raw absCorr     dFreq  
0                     1      0.9209      0.8852   2.8529  0.9209  0.023449  
1                     1      0.8301      0.8852   2.0584  0.8301  0.010747  
7                     1      0.6657      0.8842 -66.2256  0.6657  0.045432  
8                     1      0.9270      0.8842   7.6590  0.9270  0.104543  
12                    1      0.9209      0.8406   3.7654  0.9209  0.023449  

[5 rows x 28 columns]

In [8]:
s = df[['metric','model combo']]
s=s.drop_duplicates()

In [9]:
newDf = df.set_index(['metric','model combo'])
newDf.head()

metric ticker metric calcrt  \
metric                       model combo                                
Canadian National Railway Co [ 23 149]    CNR CN Equity         IS010   
                             [ 23 149]    CNR CN Equity         IS010   
                             [ 80 123]    CNR CN Equity         IS010   
                             [ 80 123]    CNR CN Equity         IS010   
                             [23 95]      CNR CN Equity         IS010   

                                                                                driver name  \
metric                       model combo                                                      
Canadian National Railway Co [ 23 149]    Segment Revenue per Carload Canadian National ...   
                             [ 23 149]    Operating Metrics - GTMs per Fuel Gallons Cons...   
                             [ 80 123]                              East Coast Diesel Price   
                             [ 80 123]                             BI NA Rail Fre Trans Cmp   
                             [23 95]      Segment Revenue per Carload Canadian National ...   

                                          driver id   driver ticker  \
metric                       model combo                              
Canadian National Railway Co [ 23 149]           23   CNR CN Equity   
                             [ 23 149]          149   CNR CN Equity   
                             [ 80 123]           80  USRD1DSL Index   
                             [ 80 123]          123  BIRAILNC Index   
                             [23 95]             23   CNR CN Equity   

                                         driver calcrt driver transformation  \
metric                       model combo                                       
Canadian National Railway Co [ 23 149]           BI047                   NaN   
                             [ 23 149]          Manual                Static   
                             [ 80 123]           PR005                   NaN   
                             [ 80 123]           PR005                   NaN   
                             [23 95]             BI047                   NaN   

                                          cofficient  rscore  \
metric                       model combo                       
Canadian National Railway Co [ 23 149]        0.6837  0.8852   
                             [ 23 149]        0.3129  0.8852   
                             [ 80 123]       -0.2273  0.8995   
                             [ 80 123]        1.0122  0.8995   
                             [23 95]          0.8976  0.8716   

                                                                           predicted_metric  \
metric                       model combo                                                      
Canadian National Railway Co [ 23 149]    1.3571|1.2813|1.3954|1.6843|1.0446|1.1458|1.29...   
                             [ 23 149]    1.3571|1.2813|1.3954|1.6843|1.0446|1.1458|1.29...   
                             [ 80 123]    1.1933|1.2595|1.0401|1.1595|1.3797|1.8788|2.04...   
                             [ 80 123]    1.1933|1.2595|1.0401|1.1595|1.3797|1.8788|2.04...   
                             [23 95]      1.2746|1.579|1.4781|1.4339|0.9908|1.5017|1.415...   

                                            ...    driver_freqency combo_size  \
metric                       model combo    ...                                 
Canadian National Railway Co [ 23 149]      ...                  Q          2   
                             [ 23 149]      ...                  Q          2   
                             [ 80 123]      ...                  W          2   
                             [ 80 123]      ...                  D          2   
                             [23 95]        ...                  Q          2   

                                         pvalue random_metric_pvalue  \
metric                       model combo          

In [10]:
idx = pd.IndexSlice
#newDf.index.get_level_values('Kansas City Southern')
# newDf.iloc[newDf.index.get_level_values('CSX Corp')]

In [11]:
newDf.ix[('Kansas City Southern')][['driver name']].head()

driver name
model combo                                                   
[37 58 69]   Segment Revenue per Carload Kansas City Southe...
[37 58 69]              Average System Dwell Time - All Trains
[37 58 69]                   Coal Stockpiles/Industrial Sector
[ 0 37]                                            Nominal GDP
[ 0 37]      Segment Revenue per Carload Kansas City Southe...

In [12]:
for row in df['model combo'].unique():
    print row
    break

[ 23 149]


In [13]:
keepCols = df.columns[4:]
allCols = ['metric','metric ticker','metric calcrt','model combo']
skipCols = allCols

allCols += [i+"_"+str(j) for j in range(1,4) for i in keepCols]
#print allCols

dataDict = {str(k): []  for k in allCols}
# print dataDict
for row in df.groupby(['metric','model combo']):
    #print row
    #print len(row[1])
    for i in range(len(row[1])+1,4):
        for col in row[1]:
            if col not in skipCols:
                dataDict[col+"_"+str(i)].append(None)
        
    for col in row[1]:
        #print len(row[1])
        #print row[1][col].iloc[cIndex]
        if col in skipCols:
            dataDict[col].append(row[1][col].iloc[0])
        else:
            for cIndex in range(len(row[1])):
                dataDict[col+"_"+str(cIndex+1)].append(row[1][col].iloc[cIndex])
        

# for k,v in dataDict.iteritems():
#     print k, len(v)
finalFrame = pd.DataFrame(dataDict)[allCols]

In [14]:
#finalFrame[finalFrame['combo_size_1']==3].sort_values(['metric','model combo']).head(10)
# finalFrame.columns

In [15]:
m =['absCorr_1','absCorr_2','absCorr_3']
n = ['dFreq_' + str(i) for i in range(1,4)]
finalFrame['uniformity'] = finalFrame[m].std(axis=1)
finalFrame['meanCorr'] = finalFrame[m].mean(axis=1)
# finalFrame['uniformity'].divide(finalFrame['combo_size_1'],axis='index').head()
comboRatios = finalFrame.groupby('metric').metric.count()*1./len(finalFrame)
# finalFrame.uniformity.head()
total =0
totalPicks = 100
comboRatios = np.around(comboRatios*totalPicks)
print comboRatios
# for k,v in zip(comboRatios.index,comboRatios):
#     temp = np.around(v*totalPicks)
#     total+=temp
#     print temp
# print total
from scipy import stats
finalFrame[pd.notnull(finalFrame['absCorr_3'])][n].apply(stats.hmean,axis=1).head()

metric
CSX Corp                        15.0
Canadian National Railway Co    17.0
Canadian Pacific Railway Ltd    17.0
Genesee & Wyoming Inc            7.0
Kansas City Southern            13.0
Norfolk Southern Corp            7.0
Union Pacific Corp              24.0
Name: metric, dtype: float64


0    0.043897
2    0.005367
3    0.005350
4    0.003223
5    0.033922
dtype: float64

In [33]:
sortFinal = finalFrame.sort_values(['uniformity','meanCorr'],ascending=[True,False])
loV = []
for metric, count in zip(comboRatios.index,comboRatios):
    loV+=(list(sortFinal[sortFinal['metric']==metric].head(int(count)).index))
    
sortFinal.iloc[loV].head().to_csv('test.csv')